{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<div class="settings-block">
  <h3>{{$title}}</h3>
{{include file="field_input.tpl" field=$address}}
{{include file="field_checkbox.tpl" field=$enabled}}
  <input type="submit" value="{{$submit}}">
</div>
