var i18n = $.extend({}, i18n || {}, {
	xgcalendar: {
		dateformat: {
			"fulldaykey": "ddMMyyyy",
			"fulldayshow": "d L yyyy",
			"separator": ".",
			"year_index": 2,
			"month_index": 1,
			"day_index": 0,
			"day": "d",
			"sun": "Su",
			"mon": "Mo",
			"tue": "Tu",
			"wed": "Mi",
			"thu": "Th",
			"fri": "Fr",
			"sat": "Sa",
			"jan": "Jan",
			"feb": "Feb",
			"mar": "Mar",
			"apr": "Apr",
			"may": "May",
			"jun": "Jun",
			"jul": "Jul",
			"aug": "Aug",
			"sep": "Sep",
			"oct": "Oct",
			"nov": "Nov",
			"dec": "Dec"
		},
		"no_implemented": "Not implemented",
		"to_date_view": "Go to today",
		"i_undefined": "Undefined",
		"allday_event": "All-day event",
		"repeat_event": "Recurring event",
		"time": "Time",
		"event": "Event",
		"location": "Loaction",
		"participant": "Attendees",
		"get_data_exception": "Exception when getting data",
		"new_event": "New event",
		"confirm_delete_event": "Do you really want to delete this event?",
		"confrim_delete_event_or_all": "Do you want to delete this event alone, or all recurrences? \r\n[OK] for this single item, [Abort] for all.",
		"data_format_error": "Data format error!",
		"invalid_title": "The title of an event must not be empty and must not contain ($<>).",
		"view_no_ready": "View is not ready",
		"example": "e.g., Meeting in room 23",
		"content": "Title",
		"create_event": "Create event",
		"update_detail": "Edit",
		"click_to_detail": "Show details",
		"i_delete": "Delete",
		"day_plural": "days",
		"others": "More: ",
		"item": ""
	}
});
